DROP TABLE IF EXISTS company;
DROP TABLE IF EXISTS computer;

CREATE TABLE company (
  id    bigint NOT NULL,
  name  varchar(255) NOT NULL,
  constraint company_pkey primary key (id)
);

CREATE TABLE computer (
    id              bigint NOT NULL,
    name            varchar(255) NOT NULL,
    manufacture_id  bigint NOT NULL,
    CONSTRAINT computer_pkey PRIMARY KEY (id)
);

ALTER TABLE computer ADD CONSTRAINT manufacture_fk 
  FOREIGN KEY (manufacture_id) REFERENCES company(id);

insert into company(id, name) values (1,'Apple Inc.');
insert into company(id, name) values (2,'Thinking Machines');
insert into company(id, name) values (3,'RCA');
insert into company(id, name) values (4,'Netronics');
insert into company(id, name) values (5,'Tandy Corporation');
insert into company(id, name) values (6,'Commodore International');
insert into company(id, name) values (7,'MOS Technology');
insert into company(id, name) values (8,'Micro Instrumentation and Telemetry Systems');
insert into company(id, name) values (9,'IMS Associates,  Inc.');
insert into company(id, name) values (10,'Digital Equipment Corporation');
insert into company(id, name) values (11,'Lincoln Laboratory');
insert into company(id, name) values (12,'Moore School of Electrical Engineering');
insert into company(id, name) values (13,'IBM');
insert into company(id, name) values (14,'Amiga Corporation');
insert into company(id, name) values (15,'Canon');
insert into company(id, name) values (16,'Nokia');
insert into company(id, name) values (17,'Sony');
insert into company(id, name) values (18,'OQO');
insert into company(id, name) values (19,'NeXT');
insert into company(id, name) values (20,'Atari');
insert into company(id, name) values (22,'Acorn ComputersRow');
insert into company(id, name) values (23,'Timex Sinclair');
insert into company(id, name) values (24,'Nintendo');
insert into company(id, name) values (25,'Sinclair Research Ltd');
insert into company(id, name) values (26,'Xerox');
insert into company(id, name) values (27,'Hewlett-Packard');
insert into company(id, name) values (28,'Zemmix');
insert into company(id, name) values (29,'ACVS');
insert into company(id, name) values (30,'Sanyo');
insert into company(id, name) values (31,'Cray');
insert into company(id, name) values (32,'Evans & Sutherland');
insert into company(id, name) values (33,'E.S.R. Inc.');
insert into company(id, name) values (34,'OMRON');
insert into company(id, name) values (35,'BBN Technologies');
insert into company(id, name) values (36,'Lenovo Group');
insert into company(id, name) values (37,'ASUS');
insert into company(id, name) values (38,'Amstrad');
insert into company(id, name) values (39,'Sun Microsystems');
insert into company(id, name) values (40,'Texas Instruments');
insert into company(id, name) values (41,'HTC Corporation');
insert into company(id, name) values (42,'Research In Motion');
insert into company(id, name) values (43,'Samsung Electronics');
insert into company(id, name) values (44,'Wang Laboratory');
insert into company(id, name) values (45,'Panasonic');	
insert into company(id, name) values (46,'Motorola');		


insert into computer(id, name, manufacture_id) values (1,'MacBook Pro 15.4 inch', 1);
insert into computer(id, name, manufacture_id) values (2,'CM-2a', 2);
insert into computer(id, name, manufacture_id) values (3,'CM-200', 2);
insert into computer(id, name, manufacture_id) values (4,'CM-5e', 2);
insert into computer(id, name, manufacture_id) values (5,'CM-5', 2);
insert into computer(id, name, manufacture_id) values (6,'MacBook Pro', 1);
insert into computer(id, name, manufacture_id) values (7,'Apple IIe', 1);
insert into computer(id, name, manufacture_id) values (8,'Apple IIc', 1);
insert into computer(id, name, manufacture_id) values (9,'Apple IIGS', 1);
insert into computer(id, name, manufacture_id) values (10,'Apple IIc Plus', 1);
insert into computer(id, name, manufacture_id) values (11,'Apple II Plus', 1);
insert into computer(id, name, manufacture_id) values (12,'Apple III', 1);
insert into computer(id, name, manufacture_id) values (13,'Apple Lisa', 1);
insert into computer(id, name, manufacture_id) values (14,'CM-2', 2);
insert into computer(id, name, manufacture_id) values (15,'Connection Machine', 2);
insert into computer(id, name, manufacture_id) values (16,'Apple II', 1);
insert into computer(id, name, manufacture_id) values (17,'Apple III Plus', 1);
insert into computer(id, name, manufacture_id) values (18,'COSMAC ELF', 3);
insert into computer(id, name, manufacture_id) values (19,'COSMAC VIP', 3);
insert into computer(id, name, manufacture_id) values (20,'ELF II', 4);
insert into computer(id, name, manufacture_id) values (21,'Macintosh', 1);
insert into computer(id, name, manufacture_id) values (22,'Macintosh II', 1);
insert into computer(id, name, manufacture_id) values (23,'Macintosh Plus', 1);
insert into computer(id, name, manufacture_id) values (24,'Macintosh IIfx', 1);
insert into computer(id, name, manufacture_id) values (25,'iMac', 1);
insert into computer(id, name, manufacture_id) values (26,'Mac Mini', 1);
insert into computer(id, name, manufacture_id) values (27,'Mac Pro', 1);
insert into computer(id, name, manufacture_id) values (28,'Power Macintosh', 1);
insert into computer(id, name, manufacture_id) values (29,'PowerBook', 1);
insert into computer(id, name, manufacture_id) values (30,'Xserve', 1);
insert into computer(id, name, manufacture_id) values (31,'Powerbook 100', 1);
insert into computer(id, name, manufacture_id) values (32,'Powerbook 140', 1);
insert into computer(id, name, manufacture_id) values (33,'Powerbook 170', 1);
insert into computer(id, name, manufacture_id) values (34,'PowerBook Duo', 1);
insert into computer(id, name, manufacture_id) values (35,'PowerBook 190', 1);
insert into computer(id, name, manufacture_id) values (36,'Macintosh Quadra', 1);
insert into computer(id, name, manufacture_id) values (37,'Macintosh Quadra 900', 1);
insert into computer(id, name, manufacture_id) values (38,'Macintosh Quadra 700', 1);
insert into computer(id, name, manufacture_id) values (39,'Macintosh LC', 1);
insert into computer(id, name, manufacture_id) values (40,'Macintosh LC II', 1);
insert into computer(id, name, manufacture_id) values (41,'Macintosh LC III', 1);
insert into computer(id, name, manufacture_id) values (42,'Macintosh LC III+', 1);
insert into computer(id, name, manufacture_id) values (43,'Macintosh Quadra 605', 1);
insert into computer(id, name, manufacture_id) values (44,'Macintosh LC 500 series', 1);
insert into computer(id, name, manufacture_id) values (45,'TRS-80 Color ComputersRow', 5);
insert into computer(id, name, manufacture_id) values (46,'Acorn System 2', 5);
insert into computer(id, name, manufacture_id) values (47,'Dragon 32/64', 5);
insert into computer(id, name, manufacture_id) values (48,'MEK6800D2', 5);
insert into computer(id, name, manufacture_id) values (49,'Newbear 77/68', 5);
insert into computer(id, name, manufacture_id) values (50,'Commodore PET', 6);
insert into computer(id, name, manufacture_id) values (51,'Commodore 64', 6);
insert into computer(id, name, manufacture_id) values (52,'Commodore 64C', 6);
insert into computer(id, name, manufacture_id) values (53,'Commodore SX-64', 6);
insert into computer(id, name, manufacture_id) values (54,'Commodore 128', 6);
insert into computer(id, name, manufacture_id) values (55,'Apple I', 1);
insert into computer(id, name, manufacture_id) values (56,'KIM-1', 7);
insert into computer(id, name, manufacture_id) values (57,'Altair 8800', 8);
insert into computer(id, name, manufacture_id) values (58,'IMSAI 8080', 9);
insert into computer(id, name, manufacture_id) values (59,'IMSAI Series Two', 9);
insert into computer(id, name, manufacture_id) values (60,'VAX', 10);
insert into computer(id, name, manufacture_id) values (61,'VAX 11/780', 10);
insert into computer(id, name, manufacture_id) values (62,'VAX 11/750', 10);
insert into computer(id, name, manufacture_id) values (63,'TX-2', 11);
insert into computer(id, name, manufacture_id) values (64,'TX-0', 11);
insert into computer(id, name, manufacture_id) values (65,'Whirlwind', 11);
insert into computer(id, name, manufacture_id) values (66,'ENIAC', 12);
insert into computer(id, name, manufacture_id) values (67,'IBM PC', 13);
insert into computer(id, name, manufacture_id) values (68,'Macintosh Classic', 1);
insert into computer(id, name, manufacture_id) values (69,'Macintosh Classic II', 1);
insert into computer(id, name, manufacture_id) values (70,'Amiga', 14);
insert into computer(id, name, manufacture_id) values (71,'Amiga 1000', 6);
insert into computer(id, name, manufacture_id) values (72,'Amiga 500', 6);
insert into computer(id, name, manufacture_id) values (73,'Amiga 500+', 6);
insert into computer(id, name, manufacture_id) values (74,'Amiga 2000', 6);
insert into computer(id, name, manufacture_id) values (75,'Amiga 3000', 6);
insert into computer(id, name, manufacture_id) values (76,'Amiga 600', 6);
insert into computer(id, name, manufacture_id) values (77,'Macintosh 128K', 1);
insert into computer(id, name, manufacture_id) values (78,'Macintosh 512K', 1);
insert into computer(id, name, manufacture_id) values (79,'Macintosh SE', 1);
insert into computer(id, name, manufacture_id) values (80,'Macintosh SE/30', 1);
insert into computer(id, name, manufacture_id) values (81,'Canon Cat', 15);
insert into computer(id, name, manufacture_id) values (82,'Nokia 770', 16);
insert into computer(id, name, manufacture_id) values (83,'Nokia N800', 16);
insert into computer(id, name, manufacture_id) values (84,'Mylo', 17);
insert into computer(id, name, manufacture_id) values (85,'OQO 02', 18);
insert into computer(id, name, manufacture_id) values (86,'OQO 01+', 18);
insert into computer(id, name, manufacture_id) values (87,'Pinwheel calculator', 18);
insert into computer(id, name, manufacture_id) values (88,'iBook', 1);
insert into computer(id, name, manufacture_id) values (89,'MacBook', 1);
insert into computer(id, name, manufacture_id) values (90,'NeXTstation', 19);
insert into computer(id, name, manufacture_id) values (91,'NeXTcube', 19);
insert into computer(id, name, manufacture_id) values (92,'NeXTstation Color Turbo', 19);
insert into computer(id, name, manufacture_id) values (93,'NeXTstation Color', 19);
insert into computer(id, name, manufacture_id) values (94,'NeXTstation Turbo', 19);
insert into computer(id, name, manufacture_id) values (95,'NeXTcube Turbo', 19);
insert into computer(id, name, manufacture_id) values (96,'NeXTcube 040', 19);
insert into computer(id, name, manufacture_id) values (97,'NeXTcube 030', 19);
insert into computer(id, name, manufacture_id) values (98,'Tinkertoy Tic-Tac-Toe ComputersRow', 19);
insert into computer(id, name, manufacture_id) values (99,'Z3', 19);
insert into computer(id, name, manufacture_id) values (100,'Z4', 19);
insert into computer(id, name, manufacture_id) values (101,'Z1', 19);
insert into computer(id, name, manufacture_id) values (102,'Z2', 19);
insert into computer(id, name, manufacture_id) values (103,'Wang 2200', 44);
insert into computer(id, name, manufacture_id) values (104,'Wang VS', 44);
insert into computer(id, name, manufacture_id) values (105,'Wang OIS', 44);
insert into computer(id, name, manufacture_id) values (106,'BBC Micro', 22);
insert into computer(id, name, manufacture_id) values (107,'IBM 650', 13);
insert into computer(id, name, manufacture_id) values (108,'Cray-1', 31);
insert into computer(id, name, manufacture_id) values (109,'Cray-3', 31);
insert into computer(id, name, manufacture_id) values (110,'Cray-2', 31);
insert into computer(id, name, manufacture_id) values (111,'Cray-4', 31);
insert into computer(id, name, manufacture_id) values (112,'Cray X1', 31);
insert into computer(id, name, manufacture_id) values (113,'Cray XD1', 31);
insert into computer(id, name, manufacture_id) values (114,'Cray T3D', 31);
insert into computer(id, name, manufacture_id) values (115,'Cray T3E', 31);
insert into computer(id, name, manufacture_id) values (116,'Cray C90', 31);
insert into computer(id, name, manufacture_id) values (117,'Cray T90', 31);
insert into computer(id, name, manufacture_id) values (118,'Cray SV1', 31);
insert into computer(id, name, manufacture_id) values (119,'Cray J90', 31);
insert into computer(id, name, manufacture_id) values (120,'Cray XT3', 31);
insert into computer(id, name, manufacture_id) values (121,'Cray CS6400', 31);
insert into computer(id, name, manufacture_id) values (122,'Atari ST', 20);
insert into computer(id, name, manufacture_id) values (123,'Amiga 2500', 14);
insert into computer(id, name, manufacture_id) values (124,'Amiga 2500', 14);
insert into computer(id, name, manufacture_id) values (125,'Amiga 4000', 14);
insert into computer(id, name, manufacture_id) values (126,'Amiga 3000UX', 6);
insert into computer(id, name, manufacture_id) values (127,'Amiga 3000T', 6);
insert into computer(id, name, manufacture_id) values (128,'Amiga 4000T', 6);
insert into computer(id, name, manufacture_id) values (129,'Amiga 1200', 6);
insert into computer(id, name, manufacture_id) values (130,'Atari 1040 STf', 20);
insert into computer(id, name, manufacture_id) values (131,'Atari 520 ST', 20);
insert into computer(id, name, manufacture_id) values (132,'Atari 520 STfm', 20);
insert into computer(id, name, manufacture_id) values (133,'Atari 1040 STe', 20);
insert into computer(id, name, manufacture_id) values (134,'Atari MEGA STe', 20);
insert into computer(id, name, manufacture_id) values (135,'Atari 520 ST+', 20);
insert into computer(id, name, manufacture_id) values (136,'Atari 520 STm', 20);
insert into computer(id, name, manufacture_id) values (137,'Atari 130 ST', 20);
insert into computer(id, name, manufacture_id) values (138,'Atari 260 ST', 20);
insert into computer(id, name, manufacture_id) values (139,'Atari MEGA ST', 20);
insert into computer(id, name, manufacture_id) values (140,'Atari 520 STf', 20);
insert into computer(id, name, manufacture_id) values (141,'Atari 1040 STfm', 20);
insert into computer(id, name, manufacture_id) values (142,'Atari 2080 ST', 20);
insert into computer(id, name, manufacture_id) values (143,'Atari 260 ST+', 20);
insert into computer(id, name, manufacture_id) values (144,'Atari 4160 STe', 20);
insert into computer(id, name, manufacture_id) values (145,'TRS-80 Color ComputersRow 2', 5);
insert into computer(id, name, manufacture_id) values (146,'TRS-80 Color ComputersRow 3', 5);
insert into computer(id, name, manufacture_id) values (147,'TRS-80 Model 1', 5);
insert into computer(id, name, manufacture_id) values (148,'Timex Sinclair 2068', 23);
insert into computer(id, name, manufacture_id) values (149,'ZX Spectrum', 25);
insert into computer(id, name, manufacture_id) values (150,'Xerox Star', 26);
insert into computer(id, name, manufacture_id) values (151,'Xerox Alto', 26);
insert into computer(id, name, manufacture_id) values (152,'Acorn Archimedes', 22);
insert into computer(id, name, manufacture_id) values (153,'Nintendo Entertainment System', 24);
insert into computer(id, name, manufacture_id) values (154,'Super Nintendo Entertainment System', 24);
insert into computer(id, name, manufacture_id) values (155,'Super Famicom', 24);
insert into computer(id, name, manufacture_id) values (156,'Nintendo GameCube', 24);
insert into computer(id, name, manufacture_id) values (157,'Game Boy line', 17);
insert into computer(id, name, manufacture_id) values (158,'PlayStation', 17);
insert into computer(id, name, manufacture_id) values (159,'PlayStation 2', 17);
insert into computer(id, name, manufacture_id) values (160,'Game & Watch', 24);
insert into computer(id, name, manufacture_id) values (161,'EDSAC', 13);
insert into computer(id, name, manufacture_id) values (162,'IBM System/4 Pi', 13);
insert into computer(id, name, manufacture_id) values (163,'IBM AP-101', 13);
insert into computer(id, name, manufacture_id) values (164,'IBM TC-1', 13);
insert into computer(id, name, manufacture_id) values (165,'IBM AP-101B', 13);
insert into computer(id, name, manufacture_id) values (166,'IBM AP-101S', 13);
insert into computer(id, name, manufacture_id) values (167,'ProLiant', 27);
insert into computer(id, name, manufacture_id) values (168,'Http://nepomuk.semanticdesktop.org/xwiki/', 27);
insert into computer(id, name, manufacture_id) values (169,'Sinclair QL', 25);
insert into computer(id, name, manufacture_id) values (170,'Sinclair ZX81', 25);
insert into computer(id, name, manufacture_id) values (171,'Sinclair ZX80', 25);
insert into computer(id, name, manufacture_id) values (172,'Atari 65XE', 20);
insert into computer(id, name, manufacture_id) values (173,'Deep Blue', 13);
insert into computer(id, name, manufacture_id) values (174,'Macintosh Quadra 650', 1);
insert into computer(id, name, manufacture_id) values (175,'Macintosh Quadra 610', 1);
insert into computer(id, name, manufacture_id) values (176,'Macintosh Quadra 800', 1);
insert into computer(id, name, manufacture_id) values (177,'Macintosh Quadra 950', 1);
insert into computer(id, name, manufacture_id) values (178,'PowerBook 160', 1);
insert into computer(id, name, manufacture_id) values (179,'PowerBook 145B', 1);
insert into computer(id, name, manufacture_id) values (180,'PowerBook 170', 1);
insert into computer(id, name, manufacture_id) values (181,'PowerBook 145', 1);
insert into computer(id, name, manufacture_id) values (182,'PowerBook G3', 1);
insert into computer(id, name, manufacture_id) values (183,'PowerBook 140', 1);
insert into computer(id, name, manufacture_id) values (184,'Macintosh IIcx', 1);
insert into computer(id, name, manufacture_id) values (185,'Powerbook 180', 1);
insert into computer(id, name, manufacture_id) values (186,'PowerBook G4', 1);
insert into computer(id, name, manufacture_id) values (187,'Macintosh XL', 1);
insert into computer(id, name, manufacture_id) values (188,'PowerBook 100', 1);
insert into computer(id, name, manufacture_id) values (189,'PowerBook 2400c', 1);
insert into computer(id, name, manufacture_id) values (190,'PowerBook 1400', 1);
insert into computer(id, name, manufacture_id) values (191,'Macintosh Quadra 630', 1);
insert into computer(id, name, manufacture_id) values (192,'Macintosh Quadra 660AV', 1);
insert into computer(id, name, manufacture_id) values (193,'Macintosh Quadra 840AV', 1);
insert into computer(id, name, manufacture_id) values (194,'PowerBook 5300', 1);
insert into computer(id, name, manufacture_id) values (195,'PowerBook 3400c', 1);
insert into computer(id, name, manufacture_id) values (196,'Macintosh Color Classic', 1);
insert into computer(id, name, manufacture_id) values (197,'Macintosh 512Ke', 1);
insert into computer(id, name, manufacture_id) values (198,'Macintosh IIsi', 1);
insert into computer(id, name, manufacture_id) values (199,'Macintosh IIx', 1);
insert into computer(id, name, manufacture_id) values (200,'PowerBook 500 series', 1);
insert into computer(id, name, manufacture_id) values (201,'Power Macintosh G3', 1);
insert into computer(id, name, manufacture_id) values (202,'Macintosh IIci', 1);
insert into computer(id, name, manufacture_id) values (203,'iMac G5', 1);
insert into computer(id, name, manufacture_id) values (204,'Power Mac G4', 1);
insert into computer(id, name, manufacture_id) values (205,'Power Macintosh 7100', 1);
insert into computer(id, name, manufacture_id) values (206,'Power Macintosh 9600', 1);
insert into computer(id, name, manufacture_id) values (207,'Power Macintosh 7200', 1);
insert into computer(id, name, manufacture_id) values (208,'Power Macintosh 7300', 1);
insert into computer(id, name, manufacture_id) values (209,'Power Macintosh 8600', 1);
insert into computer(id, name, manufacture_id) values (210,'Power Macintosh 6200', 1);
insert into computer(id, name, manufacture_id) values (211,'Power Macintosh 8100', 1);
insert into computer(id, name, manufacture_id) values (212,'Compact Macintosh', 1);
insert into computer(id, name, manufacture_id) values (213,'Power Macintosh 4400', 1);
insert into computer(id, name, manufacture_id) values (214,'Power Macintosh 9500', 1);
insert into computer(id, name, manufacture_id) values (215,'Macintosh Portable', 1);
insert into computer(id, name, manufacture_id) values (216,'EMac', 1);
insert into computer(id, name, manufacture_id) values (217,'Power Macintosh 7600', 1);
insert into computer(id, name, manufacture_id) values (218,'Power Mac G5', 1);
insert into computer(id, name, manufacture_id) values (219,'Power Macintosh 7500', 1);
insert into computer(id, name, manufacture_id) values (220,'Power Macintosh 6100', 1);
insert into computer(id, name, manufacture_id) values (221,'Power Macintosh 8500', 1);
insert into computer(id, name, manufacture_id) values (222,'Macintosh IIvi', 1);
insert into computer(id, name, manufacture_id) values (223,'Macintosh IIvx', 1);
insert into computer(id, name, manufacture_id) values (224,'IMac G3', 1);
insert into computer(id, name, manufacture_id) values (225,'IMac G4', 1);
insert into computer(id, name, manufacture_id) values (226,'Power Mac G4 Cube', 1);
insert into computer(id, name, manufacture_id) values (227,'Intel iMac', 1);
insert into computer(id, name, manufacture_id) values (228,'Deep Thought', 13);
insert into computer(id, name, manufacture_id) values (229,'Wii', 24);
insert into computer(id, name, manufacture_id) values (230,'IBM System x', 13);
insert into computer(id, name, manufacture_id) values (231,'IBM System i', 13);
insert into computer(id, name, manufacture_id) values (232,'IBM System z', 13);
insert into computer(id, name, manufacture_id) values (233,'IBM System p', 13);
insert into computer(id, name, manufacture_id) values (234,'LC 575', 13);
insert into computer(id, name, manufacture_id) values (235,'Macintosh TV', 1);
insert into computer(id, name, manufacture_id) values (236,'Macintosh Performa', 1);
insert into computer(id, name, manufacture_id) values (237,'Macintosh II series', 1);
insert into computer(id, name, manufacture_id) values (238,'Power Macintosh 6400', 1);
insert into computer(id, name, manufacture_id) values (239,'Power Macintosh 6500', 1);
insert into computer(id, name, manufacture_id) values (240,'Apple PenLite', 1);
insert into computer(id, name, manufacture_id) values (241,'Wallstreet', 13);
insert into computer(id, name, manufacture_id) values (242,'Twentieth Anniversary Macintosh', 1);
insert into computer(id, name, manufacture_id) values (243,'Power Macintosh 5500', 1);
insert into computer(id, name, manufacture_id) values (244,'iBook G3', 1);
insert into computer(id, name, manufacture_id) values (245,'Power Macintosh 5200 LC', 1);
insert into computer(id, name, manufacture_id) values (246,'Power Macintosh 5400', 1);
insert into computer(id, name, manufacture_id) values (247,'CM-1', 28);
insert into computer(id, name, manufacture_id) values (248,'MSX', 28);
insert into computer(id, name, manufacture_id) values (249,'PlayStation 3', 17);
insert into computer(id, name, manufacture_id) values (250,'MSX2', 29);
insert into computer(id, name, manufacture_id) values (251,'MSX2+', 30);
insert into computer(id, name, manufacture_id) values (252,'MSX turbo R', 30);
insert into computer(id, name, manufacture_id) values (253,'Panasonic FS A1GT', 45);
insert into computer(id, name, manufacture_id) values (254,'Panasonic FS A1ST', 45);
insert into computer(id, name, manufacture_id) values (255,'PDP-11', 10);
insert into computer(id, name, manufacture_id) values (256,'PDP-1', 10);
insert into computer(id, name, manufacture_id) values (257,'PDP-10', 10);
insert into computer(id, name, manufacture_id) values (258,'PDP-8', 10);
insert into computer(id, name, manufacture_id) values (259,'PDP-6', 10);
insert into computer(id, name, manufacture_id) values (260,'DECSYSTEM-20', 10);
insert into computer(id, name, manufacture_id) values (261,'PDP-7', 10);
insert into computer(id, name, manufacture_id) values (262,'PDP-5', 10);
insert into computer(id, name, manufacture_id) values (263,'PDP-12', 10);
insert into computer(id, name, manufacture_id) values (264,'LINC', 10);
insert into computer(id, name, manufacture_id) values (265,'PDP-14', 10);
insert into computer(id, name, manufacture_id) values (266,'PDP-15', 10);
insert into computer(id, name, manufacture_id) values (267,'PDP-16', 10);
insert into computer(id, name, manufacture_id) values (268,'Cray X2', 31);
insert into computer(id, name, manufacture_id) values (269,'Cray X-MP', 31);
insert into computer(id, name, manufacture_id) values (270,'Evans & Sutherland ES-1', 32);
insert into computer(id, name, manufacture_id) values (271,'Commodore VIC-20', 6);
insert into computer(id, name, manufacture_id) values (272,'PowerBook 150', 1);
insert into computer(id, name, manufacture_id) values (273,'MacBook Air', 1);
insert into computer(id, name, manufacture_id) values (274,'Digi-Comp I', 33);
insert into computer(id, name, manufacture_id) values (275,'Digi-Comp', 33);
insert into computer(id, name, manufacture_id) values (276,'Digi-Comp II', 33);
insert into computer(id, name, manufacture_id) values (277,'Manchester Mark I', 33);
insert into computer(id, name, manufacture_id) values (278,'Small-Scale Experimental Machine', 33);
insert into computer(id, name, manufacture_id) values (279,'Nintendo 64', 24);
insert into computer(id, name, manufacture_id) values (280,'Game Boy Advance', 24);
insert into computer(id, name, manufacture_id) values (281,'Game Boy', 24);
insert into computer(id, name, manufacture_id) values (282,'Nintendo DS Lite', 24);
insert into computer(id, name, manufacture_id) values (283,'Nintendo DS', 24);
insert into computer(id, name, manufacture_id) values (284,'Game Boy Color', 24);
insert into computer(id, name, manufacture_id) values (285,'Game Boy Advance SP', 24);
insert into computer(id, name, manufacture_id) values (286,'Virtual Boy', 24);
insert into computer(id, name, manufacture_id) values (287,'Game Boy Micro', 24);
insert into computer(id, name, manufacture_id) values (288,'Roadrunner', 13);
insert into computer(id, name, manufacture_id) values (289,'HP 9000', 27);
insert into computer(id, name, manufacture_id) values (290,'OMRON Luna-88K2', 34);
insert into computer(id, name, manufacture_id) values (291,'OMRON Luna-88K', 34);
insert into computer(id, name, manufacture_id) values (292,'Motorola series 900', 46);
insert into computer(id, name, manufacture_id) values (293,'Motorola M8120', 46);
insert into computer(id, name, manufacture_id) values (294,'Triton Dolphin System 100', 46);
insert into computer(id, name, manufacture_id) values (295,'BBN TC2000', 35);
insert into computer(id, name, manufacture_id) values (296,'WRT54G', 46);
insert into computer(id, name, manufacture_id) values (297,'ThinkPad', 36);
insert into computer(id, name, manufacture_id) values (298,'Apple Newton', 1);
insert into computer(id, name, manufacture_id) values (299,'Atanasoff-Berry ComputersRow', 37);
insert into computer(id, name, manufacture_id) values (300,'Atlas ComputersRow', 37);
insert into computer(id, name, manufacture_id) values (301,'ASUS Eee PC 901', 37);
insert into computer(id, name, manufacture_id) values (302,'ASUS Eee PC 701', 37);
insert into computer(id, name, manufacture_id) values (303,'IBM 7030', 13);
insert into computer(id, name, manufacture_id) values (304,'System/38', 13);
insert into computer(id, name, manufacture_id) values (305,'System/36', 13);
insert into computer(id, name, manufacture_id) values (306,'IBM 7090', 13);
insert into computer(id, name, manufacture_id) values (307,'IBM RT', 13);
insert into computer(id, name, manufacture_id) values (308,'System/360', 13);
insert into computer(id, name, manufacture_id) values (309,'IBM 801', 13);
insert into computer(id, name, manufacture_id) values (310,'IBM 1401', 13);
insert into computer(id, name, manufacture_id) values (311,'ASCI White', 13);
insert into computer(id, name, manufacture_id) values (312,'Blue Gene', 13);
insert into computer(id, name, manufacture_id) values (313,'ASCI Blue Pacific', 13);
insert into computer(id, name, manufacture_id) values (314,'iPhone', 1);
insert into computer(id, name, manufacture_id) values (315,'Nokia N810', 16);
insert into computer(id, name, manufacture_id) values (316,'EDSAC 2', 13);
insert into computer(id, name, manufacture_id) values (317,'Titan', 13);
insert into computer(id, name, manufacture_id) values (318,'Pilot ACE', 13);
insert into computer(id, name, manufacture_id) values (319,'HP Mini 1000', 27);
insert into computer(id, name, manufacture_id) values (320,'HP 2133 Mini-Note PC', 27);
insert into computer(id, name, manufacture_id) values (321,'Kogan Agora Pro', 27);
insert into computer(id, name, manufacture_id) values (322,'D-Series Machines', 27);
insert into computer(id, name, manufacture_id) values (323,'ZX Spectrum 48K', 25);
insert into computer(id, name, manufacture_id) values (324,'ZX Spectrum 16K', 25);
insert into computer(id, name, manufacture_id) values (325,'ZX Spectrum 128', 25);
insert into computer(id, name, manufacture_id) values (326,'ZX Spectrum +3', 38);
insert into computer(id, name, manufacture_id) values (327,'ZX Spectrum +2', 38);
insert into computer(id, name, manufacture_id) values (328,'ZX Spectrum +2A', 38);
insert into computer(id, name, manufacture_id) values (329,'ZX Spectrum +', 25);




